from debug.logger import logger
if __name__ == '__main__':
    try:
        pass
    except Exception as e:
        logger.debug(f"Exception caught: {e}")